[tool.poetry]
name = "fb-down"
version = "0.1.0"
description = ""
authors = ["x404xx <ghost.py@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
yt-dlp = "^2024.4.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
